# Generated by Django 4.1 on 2023-01-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='element_value',
            new_name='value',
        ),
    ]
